export * from './account.service';
import { AccountService } from './account.service';
export * from './activities.service';
import { ActivitiesService } from './activities.service';
export * from './boats.service';
import { BoatsService } from './boats.service';
export * from './booking.service';
import { BookingService } from './booking.service';
export * from './clientInvoice.service';
import { ClientInvoiceService } from './clientInvoice.service';
export * from './mooring.service';
import { MooringService } from './mooring.service';
export * from './ownerInvoice.service';
import { OwnerInvoiceService } from './ownerInvoice.service';
export * from './port.service';
import { PortService } from './port.service';
export * from './refunds.service';
import { RefundsService } from './refunds.service';
export * from './reviews.service';
import { ReviewsService } from './reviews.service';
export * from './services.service';
import { ServicesService } from './services.service';
export * from './technicalService.service';
import { TechnicalServiceService } from './technicalService.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AccountService, ActivitiesService, BoatsService, BookingService, ClientInvoiceService, MooringService, OwnerInvoiceService, PortService, RefundsService, ReviewsService, ServicesService, TechnicalServiceService, UsersService];
