/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActivityResourcesOutputDTO } from './activityResourcesOutputDTO';


export interface ActivityOutputDTO { 
    id?: number;
    name?: string | null;
    active?: boolean;
    price?: number;
    description?: string | null;
    activityResources?: Array<ActivityResourcesOutputDTO> | null;
}

