/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AddBoatInputDTO { 
    name: string;
    description: string;
    registration: string;
    mooringPoint: string;
    length: number;
    sleeve: number;
    capacity: number;
    motorPower: number;
    boatTypeId: number;
    dayBasePrice: number;
    hourBasePrice: number;
    supplement: number;
    mooringId?: number;
    ownerId?: string | null;
    resourcesIdList?: Array<number> | null;
    requiredBoatTitles?: Array<number> | null;
}

