/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoatResourcesOutputDTO } from './boatResourcesOutputDTO';
import { RequiredBoatTitleOutputDTO } from './requiredBoatTitleOutputDTO';
import { MooringOutputDTO } from './mooringOutputDTO';
import { BoatTypeOutputDTO } from './boatTypeOutputDTO';
import { UserOutputDTO } from './userOutputDTO';


export interface BoatOutputDTO { 
    id?: number;
    active?: boolean;
    pendingToReview?: boolean;
    createdDate?: string;
    name?: string | null;
    description?: string | null;
    registration?: string | null;
    length?: number;
    sleeve?: number;
    capacity?: number;
    motorPower?: number;
    dayBasePrice?: number | null;
    hourBasePrice?: number | null;
    price?: number | null;
    supplement?: number | null;
    boatType?: BoatTypeOutputDTO;
    mooring?: MooringOutputDTO;
    boatResources?: Array<BoatResourcesOutputDTO> | null;
    requiredBoatTitles?: Array<RequiredBoatTitleOutputDTO> | null;
    owner?: UserOutputDTO;
}

