/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourcesEnum } from './resourcesEnum';


export interface BoatResourcesOutputDTO { 
    uri?: string | null;
    main?: boolean;
    type?: ResourcesEnum;
}

