/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ServiceBookingOutputDTO } from './serviceBookingOutputDTO';
import { RefundOutputDTO } from './refundOutputDTO';
import { ActivityBookingOutputDTO } from './activityBookingOutputDTO';
import { BoatBookingOutputDTO } from './boatBookingOutputDTO';
import { ClientInvoiceLinesOutputDTO } from './clientInvoiceLinesOutputDTO';
import { UserOutputDTO } from './userOutputDTO';


export interface BookingOutputDTO { 
    id?: number;
    clientId?: string | null;
    createdDate?: string;
    entryDate?: string | null;
    departureDate?: string | null;
    totalPeople?: number;
    paid?: boolean;
    status?: string | null;
    client?: UserOutputDTO;
    boatBookings?: Array<BoatBookingOutputDTO> | null;
    serviceBookings?: Array<ServiceBookingOutputDTO> | null;
    activyBookings?: Array<ActivityBookingOutputDTO> | null;
    refunds?: Array<RefundOutputDTO> | null;
    clientInvoiceLine?: ClientInvoiceLinesOutputDTO;
}

