/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type BookingStatusEnum = 0 | 1 | 2 | 3;

export const BookingStatusEnum = {
    NUMBER_0: 0 as BookingStatusEnum,
    NUMBER_1: 1 as BookingStatusEnum,
    NUMBER_2: 2 as BookingStatusEnum,
    NUMBER_3: 3 as BookingStatusEnum
};

