/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RefundOutputDTO } from './refundOutputDTO';
import { ClientInvoiceLinesOutputDTO } from './clientInvoiceLinesOutputDTO';
import { UserOutputDTO } from './userOutputDTO';


export interface ClientInvoiceOutputDTO { 
    id?: number;
    createdDate?: string;
    paid?: boolean;
    canceled?: boolean;
    totalAmount?: number;
    clientId?: string | null;
    client?: UserOutputDTO;
    invoiceLines?: Array<ClientInvoiceLinesOutputDTO> | null;
    refunds?: Array<RefundOutputDTO> | null;
}

