/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type OwnerInvoicesEnum = 0 | 1;

export const OwnerInvoicesEnum = {
    NUMBER_0: 0 as OwnerInvoicesEnum,
    NUMBER_1: 1 as OwnerInvoicesEnum
};

