/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserOutputDTO } from './userOutputDTO';
import { BookingOutputDTO } from './bookingOutputDTO';


export interface OwnerInvoiceLinesOutputDTO { 
    bookingId?: number;
    ownerId?: string | null;
    ownerInvoiceId?: number | null;
    price?: number;
    owner?: UserOutputDTO;
    booking?: BookingOutputDTO;
}

