/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientInvoiceOutputDTO } from './clientInvoiceOutputDTO';
import { UserOutputDTO } from './userOutputDTO';


export interface RefundOutputDTO { 
    id?: number;
    description?: string | null;
    amountToReturn?: number;
    date?: string;
    bookingId?: number;
    clientInvoiceId?: number | null;
    clientInvoice?: ClientInvoiceOutputDTO;
    client?: UserOutputDTO;
}

