/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoatOutputDTO } from './boatOutputDTO';
import { UserOutputDTO } from './userOutputDTO';


export interface ReviewOutputDTO { 
    id?: number;
    description?: string | null;
    closed?: boolean;
    boat?: BoatOutputDTO;
    admin?: UserOutputDTO;
}

