/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BoatOutputDTO } from './boatOutputDTO';
import { TechnicalServiceOutputDTO } from './technicalServiceOutputDTO';
import { OwnerInvoiceOutputDTO } from './ownerInvoiceOutputDTO';


export interface TechnicalServiceBoatOutputDTO { 
    id?: number;
    boatId?: number;
    active?: boolean;
    technicalServiceId?: number;
    createdDate?: string;
    serviceDate?: string;
    done?: boolean;
    price?: number;
    description?: string | null;
    ownerInvoiceId?: number | null;
    technicalServiceBoatOutputs?: Array<TechnicalServiceBoatOutputDTO> | null;
    boat?: BoatOutputDTO;
    technicalService?: TechnicalServiceOutputDTO;
    ownerInvoice?: OwnerInvoiceOutputDTO;
}

