/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AddBoatBookingInputDTO } from './addBoatBookingInputDTO';
import { BookingStatusEnum } from './bookingStatusEnum';


export interface UpdateBookingInputDTO { 
    id?: number;
    clientId?: string | null;
    entryDate?: string | null;
    departureDate?: string | null;
    totalPeople?: number | null;
    requestCaptain?: boolean | null;
    status?: BookingStatusEnum;
    boatBookings?: Array<AddBoatBookingInputDTO> | null;
    serviceBookingIds?: Array<number> | null;
    activityBookingIds?: Array<number> | null;
}

