/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateBoatInfoInputDTO { 
    boatId?: number;
    name?: string | null;
    description?: string | null;
    registration?: string | null;
    length?: number | null;
    sleeve?: number | null;
    capacity?: number | null;
    motorPower?: number | null;
}

