/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UpdateBoatPricesInputDTO } from './updateBoatPricesInputDTO';
import { UpdateRequiredBoatTitleDTO } from './updateRequiredBoatTitleDTO';
import { UpdateBoatInfoInputDTO } from './updateBoatInfoInputDTO';


export interface UpdateBoatInputDTO { 
    boatId?: number;
    mooringId?: number | null;
    boatTypeId?: number | null;
    active?: boolean | null;
    pendingToReview?: boolean | null;
    boatInfo?: UpdateBoatInfoInputDTO;
    requiredTitles?: UpdateRequiredBoatTitleDTO;
    prices?: UpdateBoatPricesInputDTO;
}

