/**
 * FunnySail API
 * Api para administración y venta de servicios, actividades y embarcaciones.
 *
 * The version of the OpenAPI document: v1
 * Contact: 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientInvoiceOutputDTO } from './clientInvoiceOutputDTO';
import { BookingOutputDTO } from './bookingOutputDTO';


export interface UserOutputDTO { 
    userId?: string | null;
    firstName?: string | null;
    lastName?: string | null;
    receivePromotion?: boolean;
    boatOwner?: boolean;
    birthDay?: string | null;
    emailConfirmed?: boolean | null;
    email?: string | null;
    userName?: string | null;
    phoneNumber?: string | null;
    address?: string | null;
    state?: string | null;
    city?: string | null;
    country?: string | null;
    zipCode?: string | null;
    roles?: Array<string> | null;
    bookings?: Array<BookingOutputDTO> | null;
    invoices?: Array<ClientInvoiceOutputDTO> | null;
}

